import pickle

# 书籍内容
book_text = """
The story begins by introducing Harry James Potter, a seemingly ordinary 11-year-old boy living with his cruel aunt and uncle, Vernon and Petunia Dursley, and their spoiled son Dudley. Harry's life, at least at the beginning of the story, is anything but magical. He lives in a small cupboard under the stairs in the Dursleys' house at 4 Privet Drive in the town of Little Whinging, a quiet suburban area in England. Harry’s treatment by the Dursleys is harsh; they frequently belittle him, make him feel unwanted, and give him no room for joy or love. His cousin Dudley bullies him mercilessly, and Harry is always forced to take the blame for any trouble that happens in the house, regardless of whether it’s his fault.
From a young age, Harry is aware that there is something strange about the way he’s treated compared to Dudley, but he doesn’t know why. He also doesn’t understand why strange things seem to happen around him. For example, when he gets angry or upset, objects sometimes move, and odd occurrences seem to follow him wherever he goes. However, the Dursleys make sure to keep him from learning about his true nature and the world he actually belongs to, telling him only that his parents died in a car crash when he was a baby, a lie they’ve told him his whole life.
What Harry doesn’t know is that he is no ordinary child—he is a wizard, and his parents, Lily and James Potter, were both incredibly powerful wizards who were killed by the dark wizard Lord Voldemort. Voldemort had tried to kill Harry as well when he was just a baby, but something unexpected happened: Harry survived the attack, and Voldemort’s spell backfired, leaving the dark wizard nearly destroyed. Harry, though left with a lightning-shaped scar on his forehead, survived and became a symbol of hope in the wizarding world, known as “**The Boy Who Lived.”
Harry’s life with the Dursleys is filled with neglect, loneliness, and bullying. The Dursleys go to great lengths to ensure that Harry never learns about the magical world, even going so far as to move to a house on a rock in the middle of the sea when Harry’s letters from a mysterious sender begin arriving. However, no matter how much they try to keep him from the truth, Harry’s world is about to change forever.
Harry’s life is turned upside down when, on his 11th birthday, he receives his first letter addressed to him in an unusual way: "The cupboard under the stairs, 4 Privet Drive, Little Whinging, Surrey." This letter is the first of many, and it marks the beginning of Harry’s realization that he is no ordinary child. Despite the Dursleys’ frantic attempts to stop him from reading the letter, Harry finally receives one from Rubeus Hagrid, the giant Keeper of Keys and Grounds at Hogwarts School of Witchcraft and Wizardry. The letter informs Harry that he has been accepted to Hogwarts and will be trained as a wizard.
Hagrid’s arrival is dramatic—on Harry’s 11th birthday, he visits Harry at the Dursleys’ house with the shocking news. Not only does Hagrid explain that Harry is a wizard, but he also tells Harry about his true heritage, revealing that his parents were famous wizards. Harry is overwhelmed by the news, especially when he learns that he survived an attack by Lord Voldemort, the dark wizard who killed his parents. To Harry’s amazement, Hagrid also tells him that he is famous in the wizarding world as the boy who survived Voldemort’s deadly curse, making him an object of awe and reverence among witches and wizards.
In addition to the revelation about his magical heritage, Hagrid explains that Harry will attend Hogwarts, a magical school where young witches and wizards learn how to use magic, and where Harry will make new friends and discover his own potential. Hagrid also shares the story of Harry’s parents’ deaths at the hands of Voldemort and how Harry’s survival made him a hero in the magical world. This is all news to Harry, who has never known anything about magic or the wizarding world before.
As Harry absorbs the magnitude of this revelation, Hagrid also tells him that he must come with him to Diagon Alley, a hidden street in London where witches and wizards buy their magical supplies. Here, Harry will purchase all the items necessary for his first year at Hogwarts—such as a wand, books, and robes. But first, Hagrid needs to help Harry with something even more important: the truth about who he is, and why the magical world has been so keen to keep an eye on him.
The adventure truly begins when Harry boards the Hogwarts Express on Platform 9¾ at King’s Cross Station in London. This special platform, hidden from the non-magical world, is accessed by walking into the barrier between platforms 9 and 10, a piece of magic that only wizards and witches can perform. Once Harry steps through the barrier, he finds himself in a bustling station, where he boards the Hogwarts train alongside a host of other students who are heading to the famous school.
On the train, Harry meets his two future best friends, Ron Weasley and Hermione Granger. Ron, from a large, loving wizarding family, immediately becomes Harry’s closest friend, and the two bond over their shared experiences. Ron shares with Harry details about his family, including his many brothers, who have all attended Hogwarts before him, and tells him about the magical world. He is kind-hearted, loyal, and funny, and quickly becomes an indispensable ally to Harry. Ron introduces Harry to the various quirks of the wizarding world, including the concept of wizarding food and how magical creatures and spells are part of everyday life at Hogwarts.
Harry’s other new friend, Hermione Granger, is introduced as a bright and determined young witch who comes from a non-magical family. Hermione is extremely knowledgeable about magic and, although she can come across as a bit of a know-it-all at times, she quickly proves herself to be invaluable to Harry and Ron. Hermione’s love for books, her deep knowledge of magical history, and her quick thinking make her an essential part of their trio of friends.
As they chat, the trio learns more about the magical world. The train is filled with interesting characters, from students with unusual magical abilities to those who possess pets like owls and frogs. The magical world is revealed to Harry in vivid, breathtaking detail, and he begins to feel like he belongs, something he has never experienced before in his life. The journey is filled with excitement and wonder, and Harry finds himself eager to begin his new life at Hogwarts, though he’s still not quite sure what to expect.
During the journey, Harry also encounters Draco Malfoy, a wealthy and arrogant boy who tries to befriend him, but whose true nature becomes clear when he insults Ron and his family. Draco's prejudiced attitude and his superior air make him one of Harry’s first true enemies at Hogwarts. However, Harry’s new friendships with Ron and Hermione give him strength and confidence, and he begins to realize that Hogwarts will be a place where he can make his own decisions and chart his own path, away from the Dursleys’ oppressive grip.
As the train pulls into the magical Hogwarts Station, Harry is filled with anticipation. The Hogwarts Express slows to a stop, and the first-year students are ushered off the train, where they are greeted by the giant, friendly Hagrid, who helps them across the lake in small boats to the castle. The view of Hogwarts from the boat is nothing short of magical: the towering, ancient castle with its turrets and glowing windows reflects in the black waters of the lake. This is the moment that Harry begins to truly understand how different this world is from the mundane life he had known with the Dursleys. It’s the beginning of a new chapter in his life, and he’s ready to embrace it.
Upon arriving at the castle, the students are sorted into their Houses in the Great Hall, where they meet Professor McGonagall, the strict and intelligent deputy headmistress, and Professor Dumbledore, the wise and kind headmaster. Each House—Gryffindor, Hufflepuff, Ravenclaw, and Slytherin—has its own values, traditions, and colors. The Sorting Hat chooses the best House for each student, based on their personality and qualities.
For Harry, the Sorting Hat takes a moment to decide between Gryffindor and Slytherin, but it ultimately chooses Gryffindor, a House known for bravery, courage, and daring. Ron is also placed in Gryffindor, and the two friends are thrilled. Hermione is sorted into Gryffindor as well, and the trio is united under the same banner.
As Harry, Ron, and Hermione settle into their first year at Hogwarts, they begin to uncover more information about the elusive Philosopher’s Stone—an object that is central to a mysterious set of events at the school. The stone is said to have incredible powers, most notably the ability to turn any metal into pure gold and produce the Elixir of Life, which grants immortality to those who drink it.
Nicolas Flamel, a famous wizard and alchemist, is revealed to be the creator of the Stone. Flamel, along with his wife, has lived for centuries, thanks to the power of the Elixir of Life. This revelation fascinates Harry, but the true significance of the stone’s power becomes more ominous as the story progresses. The fact that the stone can provide eternal life makes it a powerful object, and it is no surprise that many people would want to possess it.
However, it is not just the legend and power of the Philosopher’s Stone that draws attention. Harry and his friends begin to suspect that someone at Hogwarts is actively searching for it. They first encounter the stone's protection in an unexpected and frightening way. One night, while sneaking around the school, they stumble upon a three-headed dog named Fluffy, who is guarding a trapdoor in the third-floor corridor. The dog is enormous, and it is clearly there to prevent anyone from getting too close to the object it is protecting.
The trio’s curiosity grows, and as they search for answers, they discover that the trapdoor leads to an underground chamber with a series of magical obstacles and challenges. These obstacles are designed to protect the stone and ensure that only someone worthy, or with great skill, can reach it. Along the way, they learn that Professor Dumbledore, the wise and protective headmaster of Hogwarts, is aware of the dangers surrounding the stone and has taken measures to safeguard it.
One of the most intriguing parts of the mystery is when Harry, Ron, and Hermione learn of the Mirror of Erised, a magical mirror that shows the deepest desire of a person’s heart. When Harry looks into the mirror, he sees himself reunited with his parents, something he has longed for since their deaths. However, Dumbledore warns him that the mirror can be dangerous if one becomes obsessed with what it shows.
The trio soon realizes that Dumbledore is not the only one interested in the Philosopher’s Stone. Professor Snape, the Potions Master, and Professor Quirrell, the shy and nervous Defense Against the Dark Arts teacher, are both acting suspiciously. Quirrell seems to be very interested in Harry’s success at the school, but his true motives are unclear. Snape, on the other hand, has a hostile attitude toward Harry and appears to have an ongoing feud with him. Despite this, Snape’s involvement in the mystery remains hidden for much of the book.
Harry, Ron, and Hermione continue to investigate, trying to put together the pieces of the puzzle. They eventually discover that Fluffy, the three-headed dog, is guarding the trapdoor that leads to the stone, but they also learn that the stone is being protected by a series of increasingly difficult magical challenges. These tests will require them to use their wits, courage, and friendship to overcome them.
As Harry, Ron, and Hermione dig deeper into the mystery of the Philosopher’s Stone, they are forced to confront the growing danger that is lurking within Hogwarts. The dark forces at work are not only present in the form of the challenges protecting the stone, but also through the presence of Lord Voldemort, the dark wizard who murdered Harry’s parents and tried to kill him when he was just a baby.
Harry’s suspicions about Voldemort’s return are confirmed when they learn the truth about Professor Quirrell. Quirrell, the seemingly harmless and cowardly Defense Against the Dark Arts teacher, is revealed to be working for Voldemort. In fact, Quirrell has been secretly hosting Voldemort’s weakened, disembodied form on the back of his head. Voldemort’s physical body was destroyed years ago after he attempted to kill Harry, but his spirit survived and sought to regain strength.
It turns out that Voldemort has been using Quirrell to attempt to steal the Philosopher’s Stone and, through it, regain a physical body. With the Elixir of Life, Voldemort believes he can restore his power and become immortal once again, making him a force that no one can defeat. Quirrell, desperate and twisted by the power of Voldemort’s influence, agrees to do his bidding.
The dark forces in the story are not just embodied by Voldemort but also by the corrupting influence of power and greed. Quirrell is a tragic figure—weak-willed and easily manipulated by Voldemort’s promises of power. Quirrell's desperation leads him to betray everyone he holds dear, and ultimately, he is consumed by the dark magic of Voldemort.
Harry, who has grown increasingly suspicious of Quirrell, confronts him in the final moments of the book. Quirrell reveals that he has been attempting to use the stone’s powers to bring Voldemort back, and it is clear that Voldemort’s spirit is taking control of Quirrell’s body. In a terrifying moment, Voldemort’s voice emerges from Quirrell, warning Harry of his plans for the future.
Despite Quirrell’s efforts, Harry manages to prevent Voldemort from obtaining the Philosopher’s Stone. The confrontation occurs in the underground chambers of Hogwarts, where Harry’s bravery and loyalty to his friends are put to the ultimate test. With the help of his mother’s love and the protection it bestowed upon him, Harry is able to prevent Voldemort from taking control. Voldemort’s attempt to steal the stone is thwarted, but not without consequences.
Quirrell, weakened and unable to withstand the dark magic that has consumed him, dies in the process. Voldemort, however, is not destroyed. He flees, vowing to return and finish what he started—his plans to regain his physical form and destroy Harry once and for all. Harry barely escapes with his life, but the encounter leaves him with a deeper understanding of the power that Voldemort wields and the gravity of the danger that still looms over the wizarding world.
In the aftermath, Professor Dumbledore explains to Harry that his survival is not just due to luck, but because of the love his mother, Lily Potter, had for him. The protection she cast upon him when she sacrificed her life to save him has remained, keeping Harry safe from Voldemort’s attempts to kill him. This selfless love is a powerful magic that Voldemort cannot understand or overcome.
Dumbledore’s revelations about love and sacrifice give Harry a new perspective on his place in the wizarding world. He realizes that his victory over Voldemort is not just a matter of strength or power, but also of the deep connections and loyalty he shares with his friends. The dark forces are far from gone, but Harry’s courage, along with the support of his friends, is a beacon of hope in a world shadowed by evil.
The tension reaches its peak as Harry, Ron, and Hermione inch closer to the truth about the Philosopher’s Stone and the threat that Lord Voldemort poses. The trio's determination leads them to uncover the final mystery—how to actually prevent Voldemort from using the stone to return to full power. The path to this discovery is fraught with danger, but their courage and resourcefulness guide them through the challenges.
As they make their way through the magical barriers that guard the stone, the stakes grow higher. In their journey to reach the final challenge, the trio faces increasingly complex obstacles that test not only their magical abilities but their character and teamwork.
One of the most memorable challenges they face is a life-sized wizard’s chess game. With the help of Ron’s strategic thinking, the trio plays a dangerous version of chess where they must control enchanted pieces that will physically move to "check" and "checkmate" their opponents. Ron takes on the role of a knight, sacrificing himself to ensure the rest of the team can reach the next stage of the game. His bravery is a pivotal moment, demonstrating his loyalty and the deep bond between the friends.
As the trio progresses, they also have to solve a potion riddle created by Professor Snape. Hermione uses her exceptional intelligence to deduce which potion to drink in order to safely proceed while also ensuring they don’t fall victim to deadly traps. The riddle highlights Hermione's quick thinking and her pivotal role in the trio’s success.
But, as they near the final chamber where the Philosopher’s Stone is hidden, they face the ultimate confrontation—Harry faces Professor Quirrell, who, as revealed earlier, is serving as a vessel for Lord Voldemort’s return. The dark wizard’s influence over Quirrell is stronger than ever, and Quirrell's body is almost entirely consumed by Voldemort’s spirit. Quirrell, who was once an anxious and weak character, has transformed into a sinister force driven by his desire for power. His loyalty to Voldemort has turned him into an entirely different person, and the consequences of his choices are tragically apparent.
When Harry finally enters the chamber, he comes face-to-face with Quirrell, who reveals that his plan has always been to use the Philosopher's Stone to restore Voldemort to physical form. Voldemort’s spirit is barely contained, and he urges Quirrell to kill Harry in order to secure the Stone. But Harry, despite being alone and afraid, refuses to give up. In a desperate act, Harry grabs hold of Quirrell, and the touch of Harry’s skin burns Quirrell. This is due to the power of his mother’s sacrifice—the love that Lily Potter gave to Harry before her death. This selfless act of love had protected Harry all along, creating a magical shield that repels evil.
Quirrell’s body, unable to withstand the touch of Harry's protection, disintegrates in pain, and the Philosopher's Stone is almost lost in the ensuing chaos. However, Harry, who has never fully understood the depth of his mother's love, instinctively understands what he must do next. He manages to prevent Voldemort from obtaining the Stone, despite the dark wizard’s attempts to manipulate and control him.
At the crucial moment, Professor Dumbledore arrives, having been alerted by the enchanted protections surrounding the Stone. He finds Harry unconscious but alive, Quirrell’s body destroyed, and Voldemort’s spirit once again fleeing. Harry’s victory is bittersweet, as he has faced the horrors of the dark forces head-on, but he realizes that Voldemort’s influence is far from over. Voldemort flees once again, but Harry has now become more than just a symbol. He is a powerful force of resistance against the dark magic that has terrorized the wizarding world for years.
In the aftermath of the confrontation, Dumbledore explains to Harry that the power that saved him was the love his mother gave him, a magic Voldemort will never understand. The magical protection that Harry carries is not something Voldemort can defeat, and this truth becomes essential in understanding why Harry is the only one capable of truly confronting Voldemort in the future.
With the Philosopher’s Stone destroyed and Voldemort once again driven back, the end of the school year is an emotional and reflective moment for Harry and his friends. Despite the battles they’ve fought and the dangers they’ve faced, the trio looks back on their first year at Hogwarts with a mixture of relief and pride. They’ve learned much about themselves, their friendship, and the world of magic.
As the students gather in the Great Hall for the final feast of the year, Dumbledore delivers his traditional end-of-year speech, which is filled with wisdom and encouragement. The headmaster praises the students for their bravery and hard work, and he also rewards the house points for the year’s achievements. The students of Gryffindor House are particularly celebrated for their courage and determination, which helped protect the Philosopher’s Stone and defeat the dark forces at work within the school.
In a dramatic and emotional moment, Gryffindor wins the House Cup. This victory is especially significant for Harry, Ron, and Hermione, as it represents not just their triumph in the face of danger but also the strength of their friendship and loyalty. Throughout the year, the trio has proven their worth and demonstrated qualities of courage, intellect, and teamwork that set them apart.
After the feast, Harry and his friends find some time to reflect on what they’ve learned and experienced. Ron, ever the loyal friend, expresses his admiration for Harry’s bravery, while Hermione is glad they were able to solve the mysteries of the year together. For Harry, the most meaningful part of the year has been the realization that he has a place in the world, a family in his friends, and a destiny that is far greater than he could have ever imagined.
But while the year ends on a note of triumph, Harry’s thoughts linger on the dangers that still lie ahead. He knows that Voldemort is not truly gone and that he will have to face the dark wizard again in the future. However, Harry now understands that he is not alone in this fight. His friends will always stand by him, and together, they are ready to confront whatever challenges the next year brings.
As the students leave Hogwarts for the summer holidays, Harry returns to the Dursleys’ house. While the prospect of spending the summer with his abusive aunt and uncle is less than appealing, Harry now has a sense of hope and purpose that he didn’t have before. He has learned that his family is not just the Dursleys—it is the people who truly care about him, like Ron, Hermione, and even Professor Dumbledore.
Dumbledore’s final words to Harry before he leaves for the summer are of particular importance. He reminds Harry that love is the most powerful form of magic, and it is this love, combined with the strength of his character, that will guide him in the years to come.
The book ends on a hopeful note, with Harry knowing that his journey has just begun, and that the challenges he will face in the future will require not only courage but also the strength that comes from his bonds with others. As he boards the train to leave Hogwarts, Harry is no longer the lonely boy who lived in a cupboard under the stairs. He is a young wizard, full of potential, facing a future that is both uncertain and filled with promise.
"""

# 创建字典，键为书名，值为书籍内容
books_dict = {
    "Harry Potter and the Philosopher's Stone": book_text
}

# 指定输出的 Pickle 文件路径
output_pickle_path = './data/HP/hp.pkl'

# 将字典序列化并保存到 Pickle 文件
with open(output_pickle_path, 'wb') as f:
    pickle.dump(books_dict, f)

print(f"书籍内容已成功序列化并保存到 {output_pickle_path}")
